language: java

jdk:
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

after_success:
  - ci/deploy-snapshot.sh

notifications:
  email: false

sudo: false
cache:
  directories:
    - $HOME/.m2
